AllCops:
  Include:
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - node_modules/**/*
    - spec/**/*
Documentation:
  Enabled: true
Rails:
  Enabled: true
Style/FileName:
  Enabled: false
AbcSize:
  Enabled: false
Style/Tab:
  Enabled: false
Style/IndentationWidth:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
