# Add configuration values here, as shown below.
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

google_app_id: "282125992004-2brs0vcr7etvk9seabb79r782kbt67ig.apps.googleusercontent.com"
google_app_secret: "H9E-8e9UVPVcDphAwLBxK5_s"
