default: &default
  adapter: postgresql
  username: postgres
  password: password
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: project-run-development

test:
  <<: *default
  database: project-run-test

production:
  <<: *default
  database: project-run-production
